import type { Metadata } from 'next';

import './globals.css';
import { Providers } from './_components/Providers';
import Controls from './_components/Controls';
import Navigation from './_components/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-dark-blue to-dark-purple text-white">
        <Providers>
          <Navigation />
          {children}
          <Controls />
        </Providers>
      </body>
    </html>
  );
}
